[package]
name = "bevy_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"
bevy_rapier3d = { version = "0.20.0", features = ["enhanced-determinism"] }
rand = "0.8.5"
serde = "1.0.152"
derive_more = "0.99.17"
